// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("Data.Entities.ComputerEntity", b =>
                {
                    b.Property<int>("ComputerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data_Produkcji")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_produkcji");

                    b.Property<string>("Karta_Graficzna")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<int>("Memory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Procesor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Producent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ComputerId");

                    b.ToTable("computer");

                    b.HasData(
                        new
                        {
                            ComputerId = 1,
                            Data_Produkcji = new DateTime(2021, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Karta_Graficzna = "Brak",
                            Memory = 8,
                            Nazwa = "Domowy",
                            Priority = 1,
                            Procesor = "Intel Core i5-12400F",
                            Producent = "MSI"
                        },
                        new
                        {
                            ComputerId = 2,
                            Data_Produkcji = new DateTime(2023, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Karta_Graficzna = "MSI GeForce RTX 4060 Gaming X 8GB",
                            Memory = 32,
                            Nazwa = "Gamingowy",
                            Priority = 1,
                            Procesor = "INTEL Core i9-13900KF",
                            Producent = "Asus"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
